name: CI Build and Artifacts

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libfuse2

      - name: Install Windows dependencies (NSIS)
        if: runner.os == 'Windows'
        run: choco install nsis --no-progress -y

      - name: Install Windows dependencies (WiX Toolset)
        if: runner.os == 'Windows'
        run: choco install wixtoolset --no-progress -y

      - name: Install JS dependencies
        run: yarn install

      - name: Build Tauri app
        run: yarn tauri build

      - name: Collect and upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FreeDiscord-${{ runner.os }}-artifacts
          if-no-files-found: error
          path: |
            src-tauri/target/**/release/bundle/**/*.dmg
            src-tauri/target/**/release/bundle/**/*.app.tar.gz
            src-tauri/target/**/release/bundle/**/*.pkg
            src-tauri/target/**/release/bundle/**/*.exe
            src-tauri/target/**/release/bundle/**/*.msi
            src-tauri/target/**/release/bundle/**/*.zip
            src-tauri/target/**/release/bundle/**/*.7z
            src-tauri/target/**/release/bundle/**/*.deb
            src-tauri/target/**/release/bundle/**/*.rpm
            src-tauri/target/**/release/bundle/**/*.AppImage
